blank_issues_enabled: false

contact_links:
  - name: Documentation | Landing Page
    url: https://docker-mailserver.github.io/docker-mailserver/latest
    about: Visit this first before opening issues!
  - name: Documentation | Environment Variables Page
    url: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/
    about: Read this page for information about mail server variables.
  - name: Documentation | Debugging Page
    url: https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/
    about: Read this page for information on how to debug DMS.
