name: Lint

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hadolint
        run: make hadolint

      - name: ShellCheck
        run: make shellcheck

      - name: ECLint
        run: make eclint
